### ISSUE TITLE
Prefer `prettier` configuration instead options from this plugin only

### ISSUE THREAD

**Issue by JounQin** [ota-meshi/eslint-plugin#58]
A `.prettierrc` file would be used constantly for all tools

**Comment by ota-meshi** [comment]
I don't remember why I chose `usePrettierrc: false` 😅, but I think it makes sense to use the prettierrc.

**Comment by JounQin** [comment]
@ota-meshi Do you have a `prettier` config set like https://github.com/1stG/configs/tree/master/packages/prettier-config for reusing across projects?

**Comment by JounQin** [comment]
> I don't have it yet. I think we can also use the Prettier defaults.

But this plugin does not?

https://github.com/ota-meshi/eslint-plugin/blob/b6b157dab9c9f6d5874e9b5b453ce74078f02ced/lib/configs/%2Bprettier.js#L27-L32

**Comment by ota-meshi** [comment]
I remembered it. The format setting seems to be based on `@mysticatea/eslint-plugin`.
https://github.com/mysticatea/eslint-plugin/blob/master/lib/configs/_override-ts.js#L64

But I'm not picky about the format setting. We can use it by default or use your preferred format.

**Comment by JounQin** [comment]
The final format is all OK to me, the point is always just constancy across projects. 😁
