### ISSUE TITLE
A mono repo for all `eslint` packages?

### ISSUE THREAD

**Issue by JounQin** [ota-meshi/eslint-plugin#59]
I do have a https://github.com/un-ts/eslint

Maybe it'll make contribution easier?

**Comment by ota-meshi** [comment]
Hmm.. I don't like monorepos because git tags are hard to manage.

**Comment by JounQin** [comment]
That's OK then, it's just personal taste.

**Comment by ota-meshi** [comment]
> Besides, git tags can/should be managed by automation tools?

I think it makes sense to introduce tools to eslint-plugin-svelte, and svelte-eslint-parser.
We probably need to apply consistent rules to the pull request titles and labels, right?

**Comment by JounQin** [comment]
> We probably need to apply consistent rules to the pull request titles and labels, right?

Sure.
